<?php
namespace app\demo\controller;
use app\demo\event\Barcode;
use app\demo\event\Menu;
use think\Hook;

class Test extends Base
{
    public function _initialize()
    {
//        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function test(){
        $data['data'] = 'jljhwdsljfla;lc';
        $data['filename'] = 'bbbbbbss';
        //生成二维码
        $ret = Barcode::makeCode($data);
        var_dump($ret);
        echo 'demo_test';
    }

    public function makeMenus(){
        Hook::listen('getMenus');
    }
}