<?php
namespace app\demo\controller;
class Test extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function test(){
        echo 'demo_test';
    }
}